# Generated by Django 4.1.7 on 2023-03-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solver_app', '0002_sudokuboard_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sudokuboard',
            name='fields',
            field=models.JSONField(default=[]),
        ),
    ]
